spring:
  application:
    name: producer-mushrooms
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27020/amap}

server:
  port: 8081

producer:
  id: mushrooms
  name: Mushroom Producer